"""Red-first spec: Span must validate its invariants at construction via
__post_init__. DO NOT EDIT THIS FILE — make it pass by changing
hooks_report/spans.py (and only what the behavior requires)."""
import pytest

from hooks_report.spans import Span


def _valid_kwargs(**overrides):
    kw = dict(
        trace_id="a" * 32,
        span_id="b" * 16,
        name="hook.test",
        kind=3,
        start_time_unix_nano=1_000,
        end_time_unix_nano=2_000,
        status_code=1,
        attributes=None,
        session_id="s1",
    )
    kw.update(overrides)
    return kw


def test_valid_span_constructs():
    span = Span(**_valid_kwargs())
    assert span.trace_id == "a" * 32


@pytest.mark.parametrize("bad_trace_id", ["", "short", "a" * 31, "a" * 33, "g" * 32])
def test_bad_trace_id_rejected(bad_trace_id):
    with pytest.raises(ValueError):
        Span(**_valid_kwargs(trace_id=bad_trace_id))


@pytest.mark.parametrize("bad_span_id", ["", "short", "b" * 15, "b" * 17, "z" * 16])
def test_bad_span_id_rejected(bad_span_id):
    with pytest.raises(ValueError):
        Span(**_valid_kwargs(span_id=bad_span_id))


@pytest.mark.parametrize("bad_kind", [0, 2, 4, -1])
def test_bad_kind_rejected(bad_kind):
    with pytest.raises(ValueError):
        Span(**_valid_kwargs(kind=bad_kind))


@pytest.mark.parametrize("bad_status", [0, 3, -1])
def test_bad_status_code_rejected(bad_status):
    with pytest.raises(ValueError):
        Span(**_valid_kwargs(status_code=bad_status))


def test_start_after_end_rejected():
    with pytest.raises(ValueError):
        Span(**_valid_kwargs(start_time_unix_nano=2_000, end_time_unix_nano=1_000))


def test_equal_start_end_allowed():
    span = Span(**_valid_kwargs(start_time_unix_nano=1_500, end_time_unix_nano=1_500))
    assert span.start_time_unix_nano == span.end_time_unix_nano
