"""Red-first spec: broken_hooks() must treat exit 1 as success for
SEMANTIC_EXIT_STEPS (findings-found), while exit 1 stays a non-success for
every other step. DO NOT EDIT THIS FILE — make it pass by changing
hooks_report/db.py (and only what the behavior requires)."""
import os
import sqlite3
import tempfile
from datetime import datetime, timedelta, timezone

import pytest

from hooks_report.config import SEMANTIC_EXIT_STEPS
from hooks_report.db import HooksDB


def _ts(hours_ago: float) -> str:
    """SQLite datetime('now')-compatible UTC timestamp string."""
    dt = datetime.now(timezone.utc) - timedelta(hours=hours_ago)
    return dt.strftime("%Y-%m-%d %H:%M:%S")


@pytest.fixture
def seeded_db_path():
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    conn = sqlite3.connect(path)
    conn.executescript("""
        CREATE TABLE hook_metrics (
            id INTEGER PRIMARY KEY,
            ts TEXT DEFAULT (datetime('now')),
            hook TEXT,
            step TEXT,
            duration_ms INTEGER,
            exit_code INTEGER,
            repo TEXT DEFAULT '',
            cmd TEXT DEFAULT '',
            session TEXT DEFAULT '',
            stderr_snippet TEXT DEFAULT ''
        );
        CREATE TABLE audit_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ts TEXT NOT NULL DEFAULT (datetime('now')),
            session TEXT NOT NULL DEFAULT '',
            tool TEXT NOT NULL DEFAULT '',
            input TEXT NOT NULL DEFAULT '',
            prev_hash TEXT DEFAULT '',
            row_hash TEXT DEFAULT ''
        );
    """)
    rows = [
        # semantic step: broken (127) two days-ish ago, then exit 1 = findings found
        ("pre-commit", "codex-review", 900, 127, _ts(30), "codex review ."),
        ("pre-commit", "codex-review", 900, 127, _ts(29), "codex review ."),
        ("pre-commit", "codex-review", 950, 1, _ts(2), "codex review ."),
        # non-semantic step: same shape — exit 1 here is a real failure
        ("pre-commit", "ruff-check", 200, 127, _ts(30), "ruff check ."),
        ("pre-commit", "ruff-check", 210, 1, _ts(2), "ruff check ."),
        # sanity: exit 0 counts as success for anyone
        ("pre-commit", "gitleaks", 400, 127, _ts(30), "gitleaks protect"),
        ("pre-commit", "gitleaks", 410, 0, _ts(1), "gitleaks protect"),
    ]
    for hook, step, dur, code, ts, cmd in rows:
        conn.execute(
            "INSERT INTO hook_metrics (hook, step, duration_ms, exit_code, ts, cmd) VALUES (?,?,?,?,?,?)",
            (hook, step, dur, code, ts, cmd),
        )
    conn.commit()
    conn.close()
    yield path
    os.unlink(path)


def _broken_by_step(db_path):
    db = HooksDB(db_path)
    try:
        return {b.step: b for b in db.broken_hooks()}
    finally:
        db.close()


def test_codex_review_is_semantic_precondition():
    assert "codex-review" in SEMANTIC_EXIT_STEPS
    assert "ruff-check" not in SEMANTIC_EXIT_STEPS


def test_semantic_step_exit_1_counts_as_success(seeded_db_path):
    broken = _broken_by_step(seeded_db_path)
    entry = broken.get("codex-review")
    assert entry is None or entry.last_success is not None, (
        "codex-review is a SEMANTIC_EXIT_STEP: its exit-1 run means 'findings "
        "found' and must register as a success, not leave last_success empty"
    )


def test_semantic_step_last_success_is_the_exit_1_run(seeded_db_path):
    broken = _broken_by_step(seeded_db_path)
    entry = broken.get("codex-review")
    if entry is not None:
        assert entry.last_success is not None
        assert entry.last_success > entry.last_fail, (
            "last_success must reflect the exit-1 run, which is newer than the 127s"
        )


def test_non_semantic_step_exit_1_is_not_success(seeded_db_path):
    broken = _broken_by_step(seeded_db_path)
    entry = broken.get("ruff-check")
    assert entry is not None, "ruff-check still has recent 127s and must be listed"
    assert entry.last_success is None, (
        "exit 1 for a non-semantic step is a genuine failure and must NOT count "
        "as a success"
    )


def test_exit_0_still_counts_for_everyone(seeded_db_path):
    broken = _broken_by_step(seeded_db_path)
    entry = broken.get("gitleaks")
    if entry is not None:
        assert entry.last_success is not None
